[rerest]
dev = true
trace = false

[http]
host = "0.0.0.0"
port = 8080

[redis]
password = ""
database_data = 0
database_control = 1
host = "redis_server"
port = 6379

[access]
    [[access.keys]]
    name = "doc"
    prefix = "doc"
    type = "set"
    read_only = true

    [[access.keys]]
    name = "doclist"
    prefix = "doclist"
    type = "list"
    read_only = true

